/*
 * adc.cpp
 *
 *  Created on: 31 мар. 2021 г.
 *      Author: Nikolay Shevyrev
 */

#include "adc.h"

void ADC_Init(){
	/*
	 * ADC123 Clock Enable
	 */
	SET_BIT(RCC->APB2ENR, RCC_APB2ENR_ADC1EN);
	SET_BIT(RCC->APB2ENR, RCC_APB2ENR_ADC2EN);

	ADCPins_Init();

	/*
	 * ADC1
	 * Channel 10
	 * VPOS
	 */
	SET_BIT(ADC1->CR1, ADC_CR1_SCAN);

	SET_BIT(ADC1->CR1, ADC_CR1_JAUTO);

	SET_BIT(ADC1->SMPR1, ADC_SMPR1_SMP10_0 | ADC_SMPR1_SMP10_1 | ADC_SMPR1_SMP10_2);

	SET_BIT(ADC1->JSQR, ADC_JSQR_JL);

	SET_BIT(ADC1->JSQR, ADC_JSQR_JSQ1_1 | ADC_JSQR_JSQ1_3);
	SET_BIT(ADC1->JSQR, ADC_JSQR_JSQ2_1 | ADC_JSQR_JSQ2_3);
	SET_BIT(ADC1->JSQR, ADC_JSQR_JSQ3_1 | ADC_JSQR_JSQ3_3);
	SET_BIT(ADC1->JSQR, ADC_JSQR_JSQ4_1 | ADC_JSQR_JSQ4_3);



	/*
	 * ADC2
	 * Channel 11
	 * VNEG
	 */
	SET_BIT(ADC2->CR1, ADC_CR1_SCAN);

	SET_BIT(ADC2->CR1, ADC_CR1_JAUTO);

	SET_BIT(ADC2->SMPR1, ADC_SMPR1_SMP11_0 | ADC_SMPR1_SMP11_1 | ADC_SMPR1_SMP11_2);

	SET_BIT(ADC2->JSQR, ADC_JSQR_JL);

	SET_BIT(ADC2->JSQR, ADC_JSQR_JSQ1_0 | ADC_JSQR_JSQ1_1 | ADC_JSQR_JSQ1_3);
	SET_BIT(ADC2->JSQR, ADC_JSQR_JSQ2_0 | ADC_JSQR_JSQ2_1 | ADC_JSQR_JSQ2_3);
	SET_BIT(ADC2->JSQR, ADC_JSQR_JSQ3_0 | ADC_JSQR_JSQ3_1 | ADC_JSQR_JSQ3_3);
	SET_BIT(ADC2->JSQR, ADC_JSQR_JSQ4_0 | ADC_JSQR_JSQ4_1 | ADC_JSQR_JSQ4_3);

}

void ADCPins_Init(){
	/*
	 * Ports Clock Enable
	 */
	GPIO_PortClockInit(V_MEAS_PORT);

	GPIO_AnalogPinInit(VPOS_PIN, V_MEAS_PORT);
	GPIO_AnalogPinInit(VNEG_PIN, V_MEAS_PORT);

}
